version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5

  - package-ecosystem: "terraform"
    directories:
    - "/terraform/**"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
